Update destroy.yml

diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -33,8 +33,8 @@ jobs:
         id: ip
         run: echo "ADMIN_CIDR=$(curl -s https://checkip.amazonaws.com)/32" >> $GITHUB_ENV
 
-      - name: Cleanup lock on failure
-        run: terraform force-unlock -force 1bb6f006-5edb-e713-8ba3-918949e23f5f || true
+#      - name: Cleanup lock on failure
+#        run: terraform force-unlock -force 1bb6f006-5edb-e713-8ba3-918949e23f5f || true
           
       - name: Terraform Destroy
         env:
